Cat.all.destroy_all
Cat.create(description: "", name: "Alimentation")
Cat.create(description: "", name: "Animaux")
Cat.create(description: "", name: "Beauté")
Cat.create(description: "", name: "Bricolage")
Cat.create(description: "", name: "Entretien")
Cat.create(description: "", name: "High Tech")
Cat.create(description: "", name: "Jardin")
Cat.create(description: "", name: "Maison")
Cat.create(description: "", name: "Santé")
Cat.create(description: "", name: "Véhicule")
Cat.create(description: "", name: "Vie pratique")
